default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
    # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: <%= ENV['PSQL_ROLE'] %>
  password: <%= ENV['PSQL_PASSWD'] %>

development:
  <<: *default
  database: project_x_development

test:
  <<: *default
  database: project_x_test

production:
  <<: *default
  database: project_x_production
